baseURL = "https://lcl.ovh/"
languageCode = "en-us"
title = "lcl.ovh – A localhost redirect server"
theme = "syna"
#enableGitInfo = true
version = "0.0.0"

disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[outputs]
home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[params]
name = "lcl.ovh"
description = "A localhost redirect server"

[params.style]
#background = "secondary"

# Theme customizations
# Assets relative to 'static/'
[params.custom]
favicon = "favicon.ico"
favicon_ico_sizes = "16x16 32x32"
favicon_png = "favicon.png"
favicon_svg = "favicon.svg"

# Optional, global disable switch for fontawesome related files
# For custom fontawesome js files use the custom.js method
[params.fontawesome]
disabled = false
pro = false

[params.colors]
primary = "#00838F"
secondary = "#868e96"
success = "#008f54"
info = "#00c9dc"
warning = "#fdf314"
danger = "#dc1200"
light = "#f8f9fa"
dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
#[[menu.main]]
#url = "/"
#name = "Home"
#weight = 10

#[[menu.footer]]
#url = "#"
#name = "Link"
#weight = 10

#[[menu.copyright_footer]]
#url = "/about"
#name = "About Us"
#weight = 10

[[menu.footer_social]]
weight = 20
name = "github"
pre = "fab fa-github-f"
url = "#"
